-- One-time whole-Booking Admission recorded by Booking Staff at the door.
-- The unique Booking constraint makes concurrent Admission attempts safe: the
-- first committed insert wins and every later attempt reports already admitted.
CREATE TABLE cineflow.admissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT       NOT NULL REFERENCES cineflow.bookings (id),
    admitted_by BIGINT       NOT NULL REFERENCES cineflow.staff_accounts (id),
    admitted_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT admissions_booking_unique UNIQUE (booking_id)
);

CREATE INDEX admissions_admitted_by_idx
    ON cineflow.admissions (admitted_by);
