-- Private application schema for the Movie catalog tracer.
CREATE TABLE cineflow.movies (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             TEXT        NOT NULL,
    synopsis          TEXT        NOT NULL,
    genre             TEXT        NOT NULL,
    runtime_minutes   INTEGER     NOT NULL CHECK (runtime_minutes > 0),
    age_rating        TEXT        NOT NULL,
    poster_url        TEXT,
    source_provider   TEXT        NOT NULL,
    external_id       TEXT        NOT NULL,
    source_refreshed_at TIMESTAMPTZ NOT NULL,
    archived_at       TIMESTAMPTZ,
    CONSTRAINT movies_provider_external_unique UNIQUE (source_provider, external_id)
);

CREATE INDEX movies_active_idx
    ON cineflow.movies (id)
    WHERE archived_at IS NULL;

INSERT INTO cineflow.movies (
    title,
    synopsis,
    genre,
    runtime_minutes,
    age_rating,
    poster_url,
    source_provider,
    external_id,
    source_refreshed_at,
    archived_at
) VALUES (
    'Nebula Express',
    'A courier crew races a sealed cargo across three colonies before the gate collapses.',
    'Adventure',
    118,
    'PG-13',
    'https://cdn.example.test/posters/nebula-express.jpg',
    'fixture',
    'nebula-express',
    TIMESTAMPTZ '2026-01-15 10:00:00+00',
    NULL
);
