-- Staff accounts, rotating refresh-token families, and Audit Events.
CREATE TABLE cineflow.staff_accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT        NOT NULL,
    password_hash  TEXT        NOT NULL,
    role           TEXT        NOT NULL,
    active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT staff_accounts_username_unique UNIQUE (username),
    CONSTRAINT staff_accounts_role_check CHECK (role IN ('BOOKING_STAFF', 'ADMINISTRATOR'))
);

CREATE INDEX staff_accounts_active_idx
    ON cineflow.staff_accounts (username)
    WHERE active IS TRUE;

CREATE TABLE cineflow.refresh_token_families (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_account_id BIGINT      NOT NULL REFERENCES cineflow.staff_accounts (id),
    revoked_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL
);

CREATE INDEX refresh_token_families_staff_idx
    ON cineflow.refresh_token_families (staff_account_id);

CREATE TABLE cineflow.refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id      BIGINT      NOT NULL REFERENCES cineflow.refresh_token_families (id),
    token_hash     TEXT        NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id BIGINT REFERENCES cineflow.refresh_tokens (id),
    created_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT refresh_tokens_hash_unique UNIQUE (token_hash)
);

CREATE INDEX refresh_tokens_family_idx
    ON cineflow.refresh_tokens (family_id);

CREATE TABLE cineflow.audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMPTZ NOT NULL,
    actor_staff_id  BIGINT REFERENCES cineflow.staff_accounts (id),
    action          TEXT        NOT NULL,
    subject_type    TEXT,
    subject_id      TEXT,
    correlation_id  TEXT
);

CREATE INDEX audit_events_occurred_at_idx
    ON cineflow.audit_events (occurred_at DESC);
