-- Immutable Hall Seat Maps. Geometry is generated at creation and then locked.
CREATE TABLE cineflow.halls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    row_count       INTEGER     NOT NULL,
    seats_per_row   INTEGER     NOT NULL,
    seat_map_locked BOOLEAN     NOT NULL DEFAULT FALSE,
    archived_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT halls_row_count_check CHECK (row_count BETWEEN 1 AND 26),
    CONSTRAINT halls_seats_per_row_check CHECK (seats_per_row BETWEEN 1 AND 40)
);

CREATE INDEX halls_active_idx
    ON cineflow.halls (id)
    WHERE archived_at IS NULL;

CREATE TABLE cineflow.seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id     BIGINT      NOT NULL REFERENCES cineflow.halls (id),
    row_label   TEXT        NOT NULL,
    seat_number INTEGER     NOT NULL,
    disabled    BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT seats_hall_identity_unique UNIQUE (hall_id, row_label, seat_number),
    CONSTRAINT seats_id_hall_unique UNIQUE (id, hall_id),
    CONSTRAINT seats_seat_number_check CHECK (seat_number > 0)
);

CREATE INDEX seats_hall_id_idx
    ON cineflow.seats (hall_id);

CREATE FUNCTION cineflow.reject_seat_identity_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
        OR NEW.hall_id IS DISTINCT FROM OLD.hall_id
        OR NEW.row_label IS DISTINCT FROM OLD.row_label
        OR NEW.seat_number IS DISTINCT FROM OLD.seat_number THEN
        RAISE EXCEPTION 'scheduling.seat_identity_immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER seats_identity_immutable
    BEFORE UPDATE ON cineflow.seats
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_seat_identity_change();

CREATE FUNCTION cineflow.reject_locked_seat_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM cineflow.halls
        WHERE id = NEW.hall_id
          AND seat_map_locked
    ) THEN
        RAISE EXCEPTION 'scheduling.seat_map_locked';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER seats_insert_when_unlocked
    BEFORE INSERT ON cineflow.seats
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_locked_seat_insert();

CREATE FUNCTION cineflow.reject_locked_seat_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM cineflow.halls
        WHERE id = OLD.hall_id
          AND seat_map_locked
    ) THEN
        RAISE EXCEPTION 'scheduling.seat_map_locked';
    END IF;
    RETURN OLD;
END;
$$;

CREATE TRIGGER seats_delete_when_unlocked
    BEFORE DELETE ON cineflow.seats
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_locked_seat_delete();

CREATE FUNCTION cineflow.reject_hall_geometry_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.row_count IS DISTINCT FROM OLD.row_count
        OR NEW.seats_per_row IS DISTINCT FROM OLD.seats_per_row
        OR (OLD.seat_map_locked AND NEW.seat_map_locked IS DISTINCT FROM TRUE) THEN
        RAISE EXCEPTION 'scheduling.seat_map_locked';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER halls_geometry_immutable
    BEFORE UPDATE ON cineflow.halls
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_hall_geometry_change();

-- Structural tables so disable and archive invariants can be enforced before Showtimes ship.
CREATE TABLE cineflow.showtimes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id    BIGINT      NOT NULL REFERENCES cineflow.halls (id),
    movie_id   BIGINT      NOT NULL REFERENCES cineflow.movies (id),
    starts_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT showtimes_id_hall_unique UNIQUE (id, hall_id)
);

CREATE INDEX showtimes_hall_id_idx ON cineflow.showtimes (hall_id);
CREATE INDEX showtimes_movie_id_idx ON cineflow.showtimes (movie_id);

CREATE TABLE cineflow.seat_claims (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id      BIGINT      NOT NULL,
    showtime_id  BIGINT      NOT NULL,
    seat_id      BIGINT      NOT NULL,
    claim_kind   TEXT        NOT NULL,
    expires_at   TIMESTAMPTZ,
    CONSTRAINT seat_claims_showtime_seat_unique UNIQUE (showtime_id, seat_id),
    CONSTRAINT seat_claims_showtime_hall_fk
        FOREIGN KEY (showtime_id, hall_id) REFERENCES cineflow.showtimes (id, hall_id),
    CONSTRAINT seat_claims_seat_hall_fk
        FOREIGN KEY (seat_id, hall_id) REFERENCES cineflow.seats (id, hall_id),
    CONSTRAINT seat_claims_kind_check CHECK (claim_kind IN ('HOLD', 'BOOKING')),
    CONSTRAINT seat_claims_hold_expiry_check CHECK (
        (claim_kind = 'HOLD' AND expires_at IS NOT NULL)
        OR (claim_kind = 'BOOKING' AND expires_at IS NULL)
    )
);

CREATE INDEX seat_claims_showtime_id_idx ON cineflow.seat_claims (showtime_id);
CREATE INDEX seat_claims_seat_id_idx ON cineflow.seat_claims (seat_id);
CREATE INDEX seat_claims_active_holds_idx
    ON cineflow.seat_claims (seat_id)
    WHERE claim_kind = 'HOLD' AND expires_at IS NOT NULL;

CREATE FUNCTION cineflow.seat_not_disableable(p_seat_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM cineflow.seat_claims c
        JOIN cineflow.showtimes s ON s.id = c.showtime_id
        WHERE c.seat_id = p_seat_id
          AND (
              (c.claim_kind = 'HOLD' AND c.expires_at > CLOCK_TIMESTAMP())
              OR (c.claim_kind = 'BOOKING' AND s.starts_at > CLOCK_TIMESTAMP())
          )
    );
$$;

CREATE FUNCTION cineflow.reject_unsafe_seat_disable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.disabled IS TRUE AND OLD.disabled IS DISTINCT FROM TRUE
        AND cineflow.seat_not_disableable(OLD.id) THEN
        RAISE EXCEPTION 'scheduling.seat_not_disableable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER seats_reject_unsafe_disable
    BEFORE UPDATE ON cineflow.seats
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_unsafe_seat_disable();

CREATE FUNCTION cineflow.reject_claim_on_disabled_seat()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    seat_disabled BOOLEAN;
BEGIN
    SELECT disabled INTO STRICT seat_disabled
    FROM cineflow.seats
    WHERE id = NEW.seat_id
    FOR UPDATE;
    IF seat_disabled THEN
        RAISE EXCEPTION 'scheduling.seat_not_claimable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER seat_claims_reject_disabled_seat
    BEFORE INSERT ON cineflow.seat_claims
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_claim_on_disabled_seat();

CREATE FUNCTION cineflow.reject_showtime_on_archived_hall()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    hall_archived BOOLEAN;
BEGIN
    SELECT archived_at IS NOT NULL INTO STRICT hall_archived
    FROM cineflow.halls
    WHERE id = NEW.hall_id
    FOR UPDATE;
    IF hall_archived THEN
        RAISE EXCEPTION 'scheduling.hall_archived';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER showtimes_require_active_hall
    BEFORE INSERT ON cineflow.showtimes
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_showtime_on_archived_hall();

CREATE TRIGGER showtimes_require_active_hall_on_move
    BEFORE UPDATE OF hall_id ON cineflow.showtimes
    FOR EACH ROW
    EXECUTE FUNCTION cineflow.reject_showtime_on_archived_hall();
