-- Online checkout: confirmed Bookings, simulated Payments, and Seat claim conversion.
CREATE TABLE cineflow.bookings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    showtime_id          BIGINT       NOT NULL REFERENCES cineflow.showtimes (id),
    email                TEXT         NOT NULL,
    booking_reference    TEXT         NOT NULL,
    admission_token_hash TEXT         NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT bookings_booking_reference_unique UNIQUE (booking_reference),
    CONSTRAINT bookings_admission_token_hash_unique UNIQUE (admission_token_hash)
);

CREATE INDEX bookings_showtime_id_idx
    ON cineflow.bookings (showtime_id);

CREATE TABLE cineflow.payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT        NOT NULL REFERENCES cineflow.bookings (id),
    amount_myr          NUMERIC(8, 2) NOT NULL,
    method              TEXT          NOT NULL,
    idempotency_key     TEXT          NOT NULL,
    request_fingerprint TEXT          NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL,
    CONSTRAINT payments_idempotency_key_unique UNIQUE (idempotency_key),
    CONSTRAINT payments_method_check CHECK (method IN ('CARD_SIMULATED')),
    CONSTRAINT payments_amount_positive_check CHECK (amount_myr > 0)
);

-- A converted claim records the Booking, Ticket Type, and stored Ticket Price for its Seat.
ALTER TABLE cineflow.seat_claims
    ADD COLUMN booking_id  BIGINT REFERENCES cineflow.bookings (id),
    ADD COLUMN ticket_type TEXT,
    ADD COLUMN price_myr   NUMERIC(8, 2),
    ADD CONSTRAINT seat_claims_ticket_type_check CHECK (ticket_type IN ('ADULT', 'CHILD'));

CREATE INDEX seat_claims_booking_id_idx
    ON cineflow.seat_claims (booking_id)
    WHERE booking_id IS NOT NULL;
