package com.cineflow.audit;

public enum AuditAction {

	STAFF_LOGIN,
	STAFF_LOGIN_FAILURE,
	STAFF_LOGOUT,
	TOKEN_REFRESH,
	TOKEN_REUSE,
	STAFF_DEACTIVATED,
	STAFF_PASSWORD_RESET,
	STAFF_CREATED,
	MOVIE_IMPORTED,
	MOVIE_REFRESHED,
	HALL_CREATED,
	SEAT_DISABLED,
	SEAT_ENABLED,
	HALL_ARCHIVED
}
